---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/monitoring.coreos.com/scrapeconfig_v1alpha1.json
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: &name node-exporter
spec:
  staticConfigs:
    - targets:
        - nas.g-eye.tech:9100
        - pikvm.internal:9100
  metricsPath: /metrics
  relabelings:
    - action: replace
      targetLabel: job
      replacement: *name
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/monitoring.coreos.com/scrapeconfig_v1alpha1.json
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: &name smartctl-exporter
spec:
  staticConfigs:
    - targets:
        - nas.g-eye.tech:9633
  metricsPath: /metrics
  relabelings:
    - action: replace
      targetLabel: job
      replacement: *name
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/monitoring.coreos.com/scrapeconfig_v1alpha1.json
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: &name pikvm
spec:
  staticConfigs:
    - targets:
        - pikvm.g-eye.tech
  metricsPath: /api/export/prometheus/metrics
  relabelings:
    - action: replace
      targetLabel: job
      replacement: *name
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/monitoring.coreos.com/scrapeconfig_v1alpha1.json
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: &name zigbee-controller
spec:
  staticConfigs:
    - targets:
        - zigbee-controller.g-eye.tech
  metricsPath: /metrics
  relabelings:
    - action: replace
      targetLabel: job
      replacement: *name
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/monitoring.coreos.com/scrapeconfig_v1alpha1.json
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: environment
spec:
  staticConfigs:
    - targets: ["192.168.0.94:8000"]
      labels:
        group: "environment"
        location: "Office"
---
# # yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/monitoring.coreos.com/scrapeconfig_v1alpha1.json
# apiVersion: monitoring.coreos.com/v1alpha1
# kind: ScrapeConfig
# metadata:
#   name: &name onepassword-connect
# spec:
#   staticConfigs:
#     - targets:
#         - nas.g-eye.tech:7070
#   metricsPath: /metrics
#   relabelings:
#     - action: replace
#       targetLabel: job
#       replacement: *name
