---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: drone
  namespace: drone
spec:
  interval: 5m
  chart:
    spec:
      chart: drone
      version: 0.6.5
      sourceRef:
        kind: HelmRepository
        name: drone-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: drone/drone
      tag: 2.25.0
    updateStrategy:
      type: Recreate
    # service:
    #   type: ClusterIP
    #   port: 80
    ingress:
      enabled: true
      className: internal
      annotations:
        kubernetes.io/ingress.class: internal
      hosts:
        - host: drone.g-eye.io
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - drone.g-eye.io
    resources:
      limits:
        cpu: 1200m
      requests:
        cpu: 100m
    persistentVolume:
      enabled: false
      storageClass: ceph-block
    env:
      DRONE_DATABASE_DRIVER: postgres
      DRONE_SERVER_HOST: drone.g-eye.io
      DRONE_SERVER_PROXY_HOST: drone.drone.svc:8080
      DRONE_SERVER_PROXY_PROTO: http
      DRONE_SERVER_PROTO: https
      DRONE_GIT_ALWAYS_AUTH: true
      DRONE_GITEA_SERVER: https://gitea.g-eye.io
      DRONE_USER_CREATE: username:context,admin:true
      DRONE_LOGS_TEXT: true
      DRONE_LOGS_PRETTY: true
      DRONE_LOGS_COLOR: true
      DRONE_LOGS_DEBUG: true
  valuesFrom:
    - targetPath: env.DRONE_GITEA_CLIENT_ID
      kind: Secret
      name: drone-secrets
      valuesKey: DRONE_GITEA_CLIENT_ID
    - targetPath: env.DRONE_GITEA_CLIENT_SECRET
      kind: Secret
      name: drone-secrets
      valuesKey: DRONE_GITEA_CLIENT_SECRET
    - targetPath: env.DRONE_RPC_SECRET
      kind: Secret
      name: drone-secrets
      valuesKey: DRONE_RPC_SECRET
    - targetPath: env.DRONE_DATABASE_DATASOURCE
      kind: Secret
      name: drone-secrets
      valuesKey: DRONE_DATABASE_DATASOURCE
