---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: drone
  namespace: drone
spec:
  interval: 5m
  chart:
    spec:
      chart: drone
      version: 0.6.5
      sourceRef:
        kind: HelmRepository
        name: drone-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: drone/drone
      tag: 2.25.0
    updateStrategy:
      type: Recreate
    # service:
    #   type: ClusterIP
    #   port: 80
    ingress:
      enabled: true
      className: internal
      annotations:
        kubernetes.io/ingress.class: internal
      hosts:
        - host: drone.${SECRET_DOMAIN}
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - drone.${SECRET_DOMAIN}
    env:
      DRONE_DATABASE_DRIVER: postgres
      DRONE_DATABASE_DATASOURCE: postgres://postgres:${SECRET_DRONE_POSTGRESQL_PASSWORD}@postgres16-rw.database/postgres?sslmode=disable
      DRONE_SERVER_HOST: drone.${SECRET_DOMAIN}
      DRONE_SERVER_PROXY_HOST: drone.drone.svc:8080
      DRONE_SERVER_PROXY_PROTO: http
      DRONE_SERVER_PROTO: https
      DRONE_GIT_ALWAYS_AUTH: true
      DRONE_GITEA_SERVER: https://gitea.${SECRET_DOMAIN}
      DRONE_USER_CREATE: username:context,admin:true
      DRONE_LOGS_TEXT: true
      DRONE_LOGS_PRETTY: true
      DRONE_LOGS_COLOR: true
      DRONE_RPC_SECRET: ${SECRET_DRONE_RPC_SECRET}
      DRONE_GITEA_CLIENT_ID: 3f14f733-3604-4366-8c8e-1ba636ddc690
      DRONE_GITEA_CLIENT_SECRET: ${SECRET_DRONE_GITEA_CLIENT_SECRET}
      DRONE_LOGS_DEBUG: true
    persistentVolume:
      enabled: false
      storageClass: ceph-block
