---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: etcd-defrag
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: etcd-defrag
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: etcd-defrag
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: etcd-defrag
subjects:
  - kind: ServiceAccount
    name: etcd-defrag
    namespace: system-upgrade
---
apiVersion: talos.dev/v1alpha1
kind: ServiceAccount
metadata:
  name: etcd-defrag
  namespace: system-upgrade
spec:
  roles:
    - os:admin
