---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
components:
  - ../../components/common
resources:
  - ./atuin/ks.yaml
  - ./bazarr/ks.yaml
  - ./changedetection/ks.yaml
  # - ./beets/ks.yaml
  - ./elgato-photo/ks.yaml
  - ./fusion/ks.yaml
  - ./garage-webui/ks.yaml
  # - ./home-assistant/ks.yaml
  - ./homepage/ks.yaml
  - ./jellyseerr/ks.yaml
  - ./karakeep/ks.yaml
  - ./kometa/ks.yaml
  - ./littlelinks/ks.yaml
  - ./mosquitto/ks.yaml
  # - ./nextcloud/ks.yaml
  - ./n8n/ks.yaml
  - ./openclaw/shared/ks.yaml
  - ./openclaw/instances/openclaw/ks.yaml
  - ./open-webui/ks.yaml
  - ./paperless/ks.yaml
  - ./paperless-ai/ks.yaml
  - ./plex/ks.yaml
  - ./prowlarr/ks.yaml
  - ./radarr/ks.yaml
  - ./notifier/ks.yaml
  - ./recommendarr/ks.yaml
  - ./recyclarr/ks.yaml
  - ./rybbit/ks.yaml
  - ./sabnzbd/ks.yaml
  - ./shlink/ks.yaml
  - ./sonarr/ks.yaml
  - ./tautulli/ks.yaml
  - ./twenty/ks.yaml
  - ./lelabo-crm/ks.yaml
