---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: garage
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: garage-secret
    template:
      engineVersion: v2
      data:
        garage.toml: |
          [admin]
          admin_token = "{{ .admin_token }}"

          [rpc]
          rpc_secret = "{{ .rpc_secret }}"
  dataFrom:
    - extract:
        key: garage
