---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/image.toolkit.fluxcd.io/imageupdateautomation_v1beta2.json
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageUpdateAutomation
metadata:
  name: elgato-photo
  namespace: default
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: home-ops-write
    namespace: default
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: flux@g-eye.io
        name: Flux
      messageTemplate: |
        chore(elgato-photo): update image

        {{range .Changed.Changes}}
        - {{.OldValue}} -> {{.NewValue}}
        {{end}}
    push:
      branch: flux/elgato-photo-image-update
  update:
    path: ./kubernetes/apps/default/elgato-photo
    strategy: Setters
