---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
  - ./externalsecret.yaml
  - ./httproute.yaml
  - ./imagerepository.yaml
  - ./imagepolicy.yaml
  - ./imageupdateautomation.yaml
  - ./harbor-registry-secret.yaml
  - ./github-auth-secret.yaml
  - ./gitrepository-write.yaml
