---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: lelabo-crm
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: lelabo-crm-secret
    template:
      engineVersion: v2
      data:
        # App
        APP_SECRET: "{{ .LELABO_CRM_APP_SECRET }}"
        LELABO_CRM_POSTGRES_USER: &dbUser "postgres"
        LELABO_CRM_POSTGRES_PASS: &dbPass "{{ .POSTGRES_SUPER_PASS }}"
        LELABO_CRM_POSTGRES_DB: &dbName "lelabo-crm"
        # Garage S3 Storage
        AWS_ACCESS_KEY_ID: "{{ .access_key }}"
        AWS_SECRET_ACCESS_KEY: "{{ .secret_key }}"
        # Google OAuth
        GOOGLE_CLIENT_ID: "{{ .GOOGLE_CLIENT_ID }}"
        GOOGLE_CLIENT_SECRET: "{{ .GOOGLE_CLIENT_SECRET }}"
        # Email/SMTP
        MAILGUN_SMTP_PASSWORD: "{{ .mailgun_authelia_smtp_password }}"
        # Postgres Init
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: postgres16-rw.databases.svc.cluster.local
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: lelabo-crm
    - extract:
        key: cloudnative-pg
    - extract:
        key: garage-s3
    - extract:
        key: authelia
