---
  # yaml-language-server: $schema=https://raw.githubusercontent.com/recyclarr/recyclarr/master/schemas/config-schema.json
  sonarr:
    sonarr_main:
      base_url: http://sonarr.default.svc.cluster.local
      api_key: !env_var SONARR_API_KEY

      delete_old_custom_formats: true
      replace_existing_custom_formats: true

      include:
        - template: sonarr-quality-definition-series
        # 1080p
        - template: sonarr-v4-quality-profile-web-1080p
        - template: sonarr-v4-custom-formats-web-1080p
        # 2160p
        - template: sonarr-v4-quality-profile-web-2160p
        - template: sonarr-v4-custom-formats-web-2160p

      quality_profiles:
        - name: WEB-1080p
        - name: WEB-2160p

      custom_formats:
        # HDR Formats
        - trash_ids:
            # Comment out the next line if you and all of your users' setups are fully DV compatible
            - 9b27ab6498ec0f31a3353992e19434ca # DV (WEBDL)

            # HDR10+ Boost - Uncomment the next two lines if any of your devices DO support HDR10+
            # - 0dad0a507451acddd754fe6dc3a7f5e7 # HDR10+ Boost
            # - 385e9e8581d33133c3961bdcdeffb7b4 # DV HDR10+ Boost
          assign_scores_to:
            - name: WEB-2160p

        - trash_ids:
            - 32b367365729d530ca1c124a0b180c64 # Bad Dual Groups
            - 82d40da2bc6923f41e14394075dd4b03 # No-RlsGroup
            - e1a997ddb54e3ecbfe06341ad323c458 # Obfuscated
            - 06d66ab109d4d2eddb2794d21526d140 # Retags
            - 1b3994c551cbb92a2c781af061f4ab44 # Scene
          assign_scores_to:
            - name: WEB-1080p
            - name: WEB-2160p

  radarr:
    radarr_main:
      base_url: http://radarr.default.svc.cluster.local
      api_key: !env_var RADARR_API_KEY

      delete_old_custom_formats: true
      replace_existing_custom_formats: true

      include:
        - template: radarr-quality-definition-sqp-streaming
        # 2160p
        - template: radarr-custom-formats-sqp-1-2160p
        - template: radarr-quality-profile-sqp-1-2160p-4k-only-imax-e

      quality_profiles:
        - name: SQP-1 (2160p)
          min_format_score: 2000

      custom_formats:
        # French Language Priority
        - trash_ids:
            - 4b900e171accbfb172729b63323ea8ca # MULTi (French + Original)
          assign_scores_to:
            - name: SQP-1 (2160p)
              score: 200

        - trash_ids:
            - 404c08fd0bd67f39b4d8e5709319094e # VFF (TRUEFRENCH)
          assign_scores_to:
            - name: SQP-1 (2160p)
              score: 150

        - trash_ids:
            - 4cafa20d5584f6ba1871d1b8941aa3cb # VOF (Version Originale Française)
          assign_scores_to:
            - name: SQP-1 (2160p)
              score: 100

        - trash_ids:
            - 52772f1cad6b5d26c2551f79bc538a50 # VFI (Version Française Internationale)
          assign_scores_to:
            - name: SQP-1 (2160p)
              score: 80

        - trash_ids:
            - b6ace47331a1d3b77942fc18156f6df6 # VFQ (Version Française Québec)
          assign_scores_to:
            - name: SQP-1 (2160p)
              score: 60

        # Unwanted/Bad releases
        - trash_ids:
            - 7a0d1ad358fee9f5b074af3ef3f9d9ef # hallowed
            - b6832f586342ef70d9c128d40c07b872 # Bad Dual Groups
            - 90cedc1fea7ea5d11298bebd3d1d3223 # EVO (no WEBDL)
            - ae9b7c9ebde1f3bd336a8cbd1ec4c5e5 # No-RlsGroup
            - 7357cf5161efbf8c4d5d0c30b4815ee2 # Obfuscated
            - 5c44f52a8714fdd79bb4d98e2673be1f # Retags
            - f537cf427b64c38c8e36298f657e4828 # Scene
          assign_scores_to:
            - name: SQP-1 (2160p)
